services:
  gtd-coach:
    build: .
    image: gtd-coach:latest
    container_name: gtd-coach
    # Use host networking to access LM Studio and Langfuse on localhost
    network_mode: host
    # Mount volumes for data persistence
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      - ./logs:/app/logs
      - ./summaries:/app/summaries
      # Mount the Python files for live editing (development)
      - ./gtd-review.py:/app/gtd-review.py:ro
      - ./langfuse_tracker.py:/app/langfuse_tracker.py:ro
      - ./graphiti_integration.py:/app/graphiti_integration.py:ro
      - ./graphiti_client.py:/app/graphiti_client.py:ro
      - ./adhd_patterns.py:/app/adhd_patterns.py:ro
      - ./generate_summary.py:/app/generate_summary.py:ro
      - ./test_langfuse.py:/app/test_langfuse.py:ro
      - ./test_graphiti_connection.py:/app/test_graphiti_connection.py:ro
      - ./migrate_to_graphiti.py:/app/migrate_to_graphiti.py:ro
      - ./timing_integration.py:/app/timing_integration.py:ro
      - ./test_timing_integration.py:/app/test_timing_integration.py:ro
      - ./analyze_timing.py:/app/analyze_timing.py:ro
      - ./timing_comparison.py:/app/timing_comparison.py:ro
      # Mount prompts for easy editing
      - ./prompts:/app/prompts:ro
      # Mount .env files (Timing API and Graphiti config)
      - ./.env:/app/.env:ro
      - ./.env.graphiti:/app/.env.graphiti:ro
    environment:
      # Pass through terminal for interactive sessions
      - TERM=xterm-256color
      # Indicate we're in Docker (for disabling audio if needed)
      - IN_DOCKER=true
      # Python unbuffered output
      - PYTHONUNBUFFERED=1
      # Graphiti integration
      - GRAPHITI_ENABLED=true
    # Keep stdin open and allocate pseudo-TTY for interactive mode
    stdin_open: true
    tty: true

  # Utility service for running tests
  test-langfuse:
    build: .
    image: gtd-coach:latest
    container_name: gtd-coach-test
    network_mode: host
    volumes:
      - ./langfuse_tracker.py:/app/langfuse_tracker.py:ro
      - ./test_langfuse.py:/app/test_langfuse.py:ro
    command: python3 test_langfuse.py
    environment:
      - PYTHONUNBUFFERED=1

  # Utility service for generating summaries
  generate-summary:
    build: .
    image: gtd-coach:latest
    container_name: gtd-coach-summary
    network_mode: host
    volumes:
      - ./data:/app/data:ro
      - ./summaries:/app/summaries
      - ./generate_summary.py:/app/generate_summary.py:ro
      - ./graphiti_integration.py:/app/graphiti_integration.py:ro
      - ./adhd_patterns.py:/app/adhd_patterns.py:ro
    command: python3 generate_summary.py
    environment:
      - PYTHONUNBUFFERED=1