services:
  # Main GTD Coach application
  gtd-coach:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: gtd-coach:latest
    container_name: gtd-coach-app
    labels:
      - "dev.orbstack.domains=gtd-coach.local"
    environment:
      # LM Studio configuration (OrbStack)
      - LM_STUDIO_URL=http://host.orb.internal:1234
      - LM_STUDIO_MODEL=${LM_STUDIO_MODEL:-meta-llama-3.1-8b-instruct}
      
      # Langfuse configuration (OrbStack compose domain)
      - LANGFUSE_HOST=${LANGFUSE_HOST:-http://langfuse-web.langfuse-prod.orb.local}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY:-}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY:-}
      
      # Timing API configuration
      - TIMING_API_KEY=${TIMING_API_KEY:-}
      - TIMING_MIN_MINUTES=${TIMING_MIN_MINUTES:-30}
      
      # FalkorDB configuration for Graphiti (OrbStack)
      - FALKORDB_HOST=${FALKORDB_HOST:-falkordb.local}
      - FALKORDB_PORT=${FALKORDB_PORT:-6379}
      - FALKORDB_DATABASE=${FALKORDB_DATABASE:-shared_gtd_knowledge}
      - GRAPHITI_GROUP_ID=${GRAPHITI_GROUP_ID:-shared_knowledge}
      - GRAPHITI_ENABLED=${GRAPHITI_ENABLED:-true}
      
      # OpenAI configuration for Graphiti
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - OPENAI_EMBEDDING_MODEL=${OPENAI_EMBEDDING_MODEL:-text-embedding-3-small}
      
      # Application settings
      - PYTHONPATH=/app
      - TEST_MODE=false
      - VERBOSE_MODE=${VERBOSE_MODE:-false}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./summaries:/app/summaries
      - ./config:/app/config:ro
    networks:
      - gtd-network
    # FalkorDB is running externally on host port 6380
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # Test runner service
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    image: gtd-coach:test
    container_name: gtd-coach-tests
    labels:
      - "dev.orbstack.domains=gtd-coach-tests.local"
    environment:
      - TEST_MODE=true
      - MOCK_EXTERNAL_APIS=${MOCK_EXTERNAL_APIS:-true}
      - FALKORDB_HOST=falkordb.local
      - FALKORDB_PORT=6379
      - FALKORDB_DATABASE=shared_gtd_knowledge_test
      - GRAPHITI_GROUP_ID=test_group
      - PYTHONPATH=/app
      - PYTEST_WORKERS=${PYTEST_WORKERS:-auto}
    volumes:
      - ./tests:/app/tests:ro
      - ./gtd_coach:/app/gtd_coach:ro
      - ./test-results:/app/test-results
      - ./.pytest_cache:/app/.pytest_cache
    networks:
      - gtd-network
    profiles:
      - test
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # Development environment with hot reload
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: gtd-coach:dev
    container_name: gtd-coach-dev
    labels:
      - "dev.orbstack.domains=gtd-coach-dev.local"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - LM_STUDIO_URL=http://host.orb.internal:1234
      - FALKORDB_HOST=falkordb.local
      - FALKORDB_PORT=6379
      - FALKORDB_DATABASE=shared_gtd_knowledge
      - GRAPHITI_GROUP_ID=shared_knowledge
      - PYTHONPATH=/app
    volumes:
      - .:/app  # Mount entire directory for hot reload
      - /app/.venv  # Exclude virtual env if it exists
    networks:
      - gtd-network
    profiles:
      - dev
    command: /bin/bash
    stdin_open: true
    tty: true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # Langfuse test service
  test-langfuse:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: gtd-coach:latest
    container_name: gtd-coach-langfuse-test
    labels:
      - "dev.orbstack.domains=gtd-coach-langfuse-test.local"
    environment:
      - LM_STUDIO_URL=http://host.orb.internal:1234
      - LANGFUSE_HOST=${LANGFUSE_HOST:-http://langfuse-web.langfuse-prod.orb.local}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY:-}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY:-}
      - PYTHONPATH=/app
      - TEST_MODE=true
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - gtd-network
    command: python3 test_langfuse.py
    profiles:
      - test
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # Summary generator service
  generate-summary:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: gtd-coach:latest
    container_name: gtd-coach-summary
    labels:
      - "dev.orbstack.domains=gtd-coach-summary.local"
    environment:
      - LM_STUDIO_URL=http://host.orb.internal:1234
      - FALKORDB_HOST=falkordb.local
      - FALKORDB_PORT=6379
      - FALKORDB_DATABASE=shared_gtd_knowledge
      - GRAPHITI_GROUP_ID=shared_knowledge
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
      - ./summaries:/app/summaries
    networks:
      - gtd-network
    command: python3 scripts/generate_summary.py
    profiles:
      - tools
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  gtd-network:
    driver: bridge

# FalkorDB runs externally, no volumes needed for database